---
- hosts: localhost
  gather_facts: False
  tasks:
  - name: Add jumpbox host
    add_host:
      name: workstation-{{ OSP_GUID }}.rhpds.opentlc.com
      group: jumpbox

- hosts: jumpbox
  remote_user: mcchae-pentalink.co.kr
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: ~/.ssh/opentlc_key
  roles:
    - osp-workstation
