---
- hosts: localhost
  gather_facts: False
  tasks:
  - name: Add jumpbox host
    add_host:
      name: workstation-{{ OSP_GUID }}.rhpds.opentlc.com 
      group: jumpbox

- hosts: jumpbox
  tasks:
  - name: Download RHEL image
    get_url:
      url: http://www.opentlc.com/download/osp_advanced_networking/rhel-guest-image-7.2-20151102.0.x86_64.qcow2
      dest: /tmp/rhel.qcow2
    tags:
      - tested

  - name: Create a RHEL template
    os_image:
      cloud: ospcloud
      name: rhel-guest
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /tmp/rhel.qcow2
    tags:
      - tested

  - name: Create OSP Network
    include_role:
     name: osp-network

  - name: Create a Key Pair
    include_role:
      name: osp-keypair

  - name: Create Security Groups
    include_role:
      name: osp-securitygroup

  - name: Create a flavor
    include_role:
      name: osp-flavor

