---
- hosts: localhost
  gather_facts: False
  tasks:
  - name: Add jumpbox host
    add_host:
      name: workstation-{{ OSP_GUID }}.rhpds.opentlc.com
      group: jumpbox

- hosts: jumpbox
  tasks:
  - name: Remove all instance
    include_role:
       name: osp-remove-instances
       vars_from: "{{ item }}"
    loop:
      - frontend.yaml
      - app1.yaml
      - app2.yaml
      - db.yaml
