---
- hosts: localhost
  gather_facts: False
  tasks:
  - name: Add jumpbox host
    add_host:
      name: workstation-{{ OSP_GUID }}.rhpds.opentlc.com
      group: jumpbox

- hosts: jumpbox
  gather_facts: true
  roles:
  - name: osp-facts

- hosts: frontends
  gather_facts: False
  tasks:
  - name: Curl Webside
    uri:
     url: "http://{{ item }}"
     return_content: yes
    with_items:
      - "{{ inventory_hostname }}"
#      - "{{ openstack_info.ansible_facts.openstack_servers }}"
